Transporte/Transporte/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Transporte.Repositories.EntityFramework.TransporteDB;
using Transporte.Repositories.EntityFramework;
using Transporte.Models;

namespace Transporte.Controllers
{
    public class ClienteController : Controller
    {
        private readonly TransporteUnitOfWork _context;

        // GET: Cliente
        public ActionResult ClienteIndex()
        {
            using (var unit = new TransporteUnitOfWork(new TransporteDBContext()))
            {
                return View(unit.Clientes.GetList().ToList());
            }    
        }

        public ActionResult ClienteCreate()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ClienteCreate(Cliente clientes)
        {
            if (ModelState.IsValid)
            {
                using (var unit = new TransporteUnitOfWork(new TransporteDBContext()))
                {
                    unit.Clientes.Insert(clientes);
                    unit.Complete();
                }

                return RedirectToAction("ClienteIndex");
            }

            return View();
        }

        public ActionResult ClienteUpdate(int id)
        {
            using (var unit = new TransporteUnitOfWork(new TransporteDBContext()))
            {
 
                return View(unit.Clientes.GetById(id));
            }
            
        }

        [HttpPost]
        public ActionResult ClienteUpdate(Cliente clientes)
        {

            using (var unit = new TransporteUnitOfWork(new TransporteDBContext()))
            {

                unit.Clientes.Update(clientes);
                unit.Complete();

                return RedirectToAction("ClienteIndex");
            }
   
        }

        public ActionResult ClienteDelete(int id)
        {
            using (var unit = new TransporteUnitOfWork(new TransporteDBContext()))
            {

                return View(unit.Clientes.GetById(id));
            }
        }

        [HttpPost]
        //[ActionName("Delete")] esto es para que me reconozca a traves de la vista ya que la vista llama el post
        public ActionResult ClienteDelete(Cliente clientes)
        {
            using (var unit = new TransporteUnitOfWork(new TransporteDBContext()))
            {
                var nuevoCliente = unit.Clientes.GetById(clientes.IdCliente);
                unit.Clientes.Delete(nuevoCliente);
                unit.Complete();

                return RedirectToAction("ClienteIndex");
            }
        }
    }
}

Transporte/Transporte/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Transporte.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Entrar()
        {
            return View();
        }
    }
}

Transporte/Transporte/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Transporte.Controllers
{
    public class MenuController : Controller
    {
        // GET: Menu
        public ActionResult Inicio()
        {
            return View();
        }
    }
}

Transporte/Transporte/Views/Cliente/ClienteCreate.cshtml
@model Transporte.Models.Cliente
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ClienteCreate</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <section class="text-center">
            <h4>Registro de Nuevo Cliente</h4>
        </section>
        <div>
            @Html.ActionLink("Back to List", "ClienteIndex")
        </div>
        <div class="form-horizontal">
            @*<h4>Cliente</h4>*@
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.Razon, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Razon, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Razon, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Documento, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Documento, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Documento, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Contacto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Contacto, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Contacto, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IdUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.IdUsuario, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IdUsuario, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @*@Html.LabelFor(model => model.Tipo_Documento, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <label for="inputNombre" class="col-md-2 control-label">Tipo Documento</label>
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Tipo_Documento, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tipo_Documento, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="text-align: center">
                @*<button class="btn btn-success" type="button" ng-click="GrabarDatos()">Registrar</button>*@
                <input type="submit" value="Registrar" class="btn btn-primary" />

            </div>

            @*<div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>*@
        </div>
    }


</body>
</html>

Transporte/Transporte/Views/Cliente/ClienteDelete.cshtml
@model Transporte.Models.Cliente
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ClienteDelete</title>
</head>
<body>
    @*<h3>Are you sure you want to delete this?</h3>*@
    <h3>¿Está seguro de eliminar este Cliente?</h3>
    <div>
        @*<h4>Cliente</h4>*@
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.IdCliente)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IdCliente)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Razon)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Razon)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Documento)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Documento)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Contacto)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Contacto)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Telefono)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Telefono)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Celular)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Celular)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Estado)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Estado)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IdUsuario)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IdUsuario)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Tipo_Documento)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Tipo_Documento)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(item => item.IdCliente)
            @Html.HiddenFor(item => item.Razon)
            @Html.HiddenFor(item => item.Documento)
            @Html.HiddenFor(item => item.Contacto)
            @Html.HiddenFor(item => item.Telefono)
            @Html.HiddenFor(item => item.Celular)
            @Html.HiddenFor(item => item.Email)
            @Html.HiddenFor(item => item.Estado)
            @Html.HiddenFor(item => item.IdUsuario)
            @Html.HiddenFor(item => item.Tipo_Documento)
            <div class="form-actions no-color">
                <input type="submit" value="Eliminar" class="btn btn-danger" /> |
                @Html.ActionLink("Back to List", "ClienteIndex")
            </div>
        }
    </div>
</body>
</html>

Transporte/Transporte/Views/Cliente/ClienteIndex.cshtml
@model IEnumerable<Transporte.Models.Cliente>
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ClienteIndex</title>
</head>
<body>
    @*<section class="content-header">
            <h1>
                Listado de Clientes
            </h1>
        </section>*@
    <section class="text-center">
        <h4>Listado de Clientes</h4>
    </section>
    <section class="content">
        <p>
            @Html.ActionLink("Nuevo Cliente", "ClienteCreate")
        </p>
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-body">
                        <table id="example" class="table table-striped table-bordered table-hover">
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.IdCliente)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Razon)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Documento)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Contacto)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Telefono)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Celular)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Email)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Estado)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.IdUsuario)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Tipo_Documento)
                                </th>
                                <th></th>
                            </tr>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.IdCliente)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Razon)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Documento)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Contacto)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Telefono)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Celular)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Email)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Estado)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.IdUsuario)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Tipo_Documento)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Editar", "ClienteUpdate", new { id = item.IdCliente }) |
                                        @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
                                        @Html.ActionLink("Eliminar", "ClienteDelete", new { id = item.IdCliente })
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

Transporte/Transporte/Views/Cliente/ClienteUpdate.cshtml
@model Transporte.Models.Cliente

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ClienteUpdate</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <section class="text-center">
            <h4>Editar Cliente</h4>
        </section>
        <div>
            @Html.ActionLink("Back to List", "ClienteIndex")
        </div>
        <div class="form-horizontal">
            @*<h4>Cliente</h4>*@
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.IdCliente, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.IdCliente, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IdCliente, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Razon, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Razon, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Razon, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Documento, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Documento, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Documento, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Contacto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Contacto, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Contacto, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IdUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.IdUsuario, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IdUsuario, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Tipo_Documento, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Tipo_Documento, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tipo_Documento, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="text-align: center">
                @*<button class="btn btn-success" type="button" ng-click="GrabarDatos()">Registrar</button>*@
                <input type="submit" value="Modificar Datos" class="btn btn-primary" />

            </div>

            @*<div class="form-group">
                <div class="col-md-offset-2 col-md-8">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>*@
        </div>
    }


</body>
</html>

Transporte/Transporte/Views/Login/Entrar.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V12</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    @*<link rel="icon" type="image/png" href="images/icons/favicon.ico" />*@
    <link src="~/Component/images/icons/favicon.ico" type="image/png" rel="icon" />


    <!--===============================================================================================-->
    @*<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">*@
    <link href="~/Component/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />


    <!--===============================================================================================-->
    @*<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">*@
    <link href="~/Component/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" />


    <!--===============================================================================================-->
    @*<link rel="stylesheet" type="text/css" href="fonts/Linearicons-Free-v1.0.0/icon-font.min.css">*@
    <link href="~/Component/fonts/Linearicons-Free-v1.0.0/icon-font.min.css" rel="stylesheet" />


    <!--===============================================================================================-->
    @*<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">*@
    <link href="~/Component/vendor/animate/animate.css" rel="stylesheet" />


    <!--===============================================================================================-->
    @*<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">*@
    <link href="~/Component/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" />


    <!--===============================================================================================-->
    @*<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">*@
    <link href="~/Component/vendor/select2/select2.min.css" rel="stylesheet" />


    <!--===============================================================================================-->
    @*<link rel="stylesheet" type="text/css" href="css/util.css">*@
    <link href="~/Component/vendor/css/util.css" rel="stylesheet" />

    @*<link rel="stylesheet" type="text/css" href="css/main.css">*@
    <link href="~/Component/vendor/css/main.css" rel="stylesheet" />

    <!--===============================================================================================-->
</head>
<body>

    <div class="limiter">
        <div class="container-login100" style="background-image: url('images/img-01.jpg');">
            <div class="wrap-login100 p-t-190 p-b-30">
                <form class="login100-form validate-form">
                    <div class="login100-form-avatar">
                        <img src="images/avatar-01.jpg" alt="AVATAR">
                    </div>

                    <span class="login100-form-title p-t-20 p-b-45">
                        John Doe
                    </span>

                    <div class="wrap-input100 validate-input m-b-10" data-validate="Username is required">
                        <input class="input100" type="text" name="username" placeholder="Username">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-user"></i>
                        </span>
                    </div>

                    <div class="wrap-input100 validate-input m-b-10" data-validate="Password is required">
                        <input class="input100" type="password" name="pass" placeholder="Password">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-lock"></i>
                        </span>
                    </div>

                    <div class="container-login100-form-btn p-t-10">
                        <button class="login100-form-btn" >                            
                            @Html.ActionLink("Login", "Inicio", "Menu")
                        </button>
                    </div>

                    @*<div class="text-center w-full p-t-25 p-b-230">
                        <a href="#" class="txt1">
                            Forgot Username / Password?
                        </a>
                    </div>*@

                    <div class="text-center w-full">
                        <a class="txt1" href="#">
                            Create new account
                            <i class="fa fa-long-arrow-right"></i>
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>




    <!--===============================================================================================-->
    @*<script src="vendor/jquery/jquery-3.2.1.min.js"></script>*@
    <script src="~/Component/js/jquery-3.2.1.min.js"></script>

    <!--===============================================================================================-->
    @*<script src="vendor/bootstrap/js/popper.js"></script>*@
    <script src="~/Component/js/popper.js"></script>

    @*<script src="vendor/bootstrap/js/bootstrap.min.js"></script>*@
    <script src="~/Component/js/bootstrap.min.js"></script>

    <!--===============================================================================================-->
    @*<script src="vendor/select2/select2.min.js"></script>*@
    <script src="~/Component/vendor/select2/select2.min.js"></script>

    <!--===============================================================================================-->
    @*<script src="js/main.js"></script>*@
    <script src="~/Component/js/main.js"></script>

</body>
</html>